### PR TITLE
Update hacktoberfest-package-repos.md

### PR DESCRIPTION
**Pull request by TimGeyssens**
Adds UIOMatic

### CODE REVIEW

**Comment by jmayntzhusen** [comment]
Hey Tim!

Happy to see you adding your package to the list 🙂

Would be super nice if you had a help wanted or up for grabs or similar label that you could link directly to so prospective contributors can get a nice overview of tasks that they know they can work on. Not sure on the status of all of the issues on your list, some of them are tagged with needs investigation fx, does that mean they are ready for anyone to pick up?

**Comment by TimGeyssens** [comment]
Sure will do!

**Comment by TimGeyssens** [comment]
Updated some issues with help wanted, will add some more stuff https://github.com/TimGeyssens/UIOMatic/issues

**Comment by TimGeyssens** [comment]
Updated the pull request to link to https://github.com/TimGeyssens/UIOMatic/labels/help%20wanted

**Comment by jmayntzhusen** [comment]
Thanks ☺

Yep of course you are very welcome to continue adding issues, also during Hacktoberfest itself! I resolved a merge conflict and will merge this now, let's hope it drives contributors to your package 😉

**Comment by TimGeyssens** [comment]
Thanks!

**Pull request merged**
