### PR TITLE
Update hacktoberfest-package-repos.md

### PR DESCRIPTION
**Pull request by readingdancer**
Adding two more packages that could do with some help ( fyi, I will be adding some more issues to the packages later today :) )

### CODE REVIEW

**Comment by LottePitcher** [comment]
Thanks @readingdancer! And well done for adding the 'hacktoberfest' tag to those repos already!

Are all the issues going to be ones that you would like help on? If you end up realising that it makes sense to add 'help-wanted' or 'up-for-grabs' labels to a subset then please come back and update your URLs to be the filtered list.  

Good luck with the issue reporting!

**Comment by readingdancer** [comment]
Hi @LottePitcher 

I have added the "help-wanted" label and added new issues, if I think of anything else, I will add them over the next few days, but for now, I think it's good to merge in my project URL's.

Cheers, Chris

**Comment by jmayntzhusen** [comment]
This is great Chris! Let's hope some people are encouraged to help out on your packages! 😊

**Comment by readingdancer** [comment]
Thanks @jmayntzhusen at the very least, it has made me re-visit the packages and I'll probably take a look at the issues I have raised if no one else does this month :)

**Comment by LottePitcher** [comment]
Sounds like a win-win then!

**Pull request merged**
